**Shubham Gopal Raul**  
*CB.EN.P2AEL23023*<br> 

## <center>21BM681 Machine Learning and Embedded Programming Lab 1</center>

1. Generate a sample with 10 features. 


In [1]:
import pandas as pd
import numpy as np
import statistics as stats

In [2]:
np.random.seed(100)
ans1 = np.random.rand(1,10)
print(ans1)

[[0.54340494 0.27836939 0.42451759 0.84477613 0.00471886 0.12156912
  0.67074908 0.82585276 0.13670659 0.57509333]]


<br>
2. Create a dataset of size 10x10  

In [3]:
names,li = ['A','B','C','D','E','F','G','H','I','J'],[]
np.random.seed(100)
for i in range(0,len(names)):
    li.append([names[i],int(np.random.randint(40,100,size=1)),int(np.random.randint(40,100,size=1)),int(np.random.randint(40,100,size=1)),int(np.random.randint(40,100,size=1)),int(np.random.randint(40,100,size=1)),int(np.random.randint(40,100,size=1)),int(np.random.randint(40,100,size=1)),int(np.random.randint(40,100,size=1)),int(np.random.randint(40,100,size=1))])
ans2 = pd.DataFrame(li,columns=['Name','Sub1','Sub2','Sub3','Sub4','Sub5','Sub6','Sub7','Sub8','Sub9'])
ans2

Name  Sub1  Sub2  Sub3  Sub4  Sub5  Sub6  Sub7  Sub8  Sub9
0    A    48    64    43    79    63    55    88    50    70
1    B    92    74    93    42    74    54    74    89    88
2    C    64    55    76    83    98    56    99    49    69
3    D    62    42    67    84    44    71    41    53    93
4    E    59    76    44    67    99    43    47    89    87
5    F    41    54    95    47    99    56    42    97    81
6    G    70    59    74    93    67    96    86    89    70
7    H    88    87    79    85    78    84    58    40    96
8    I    74    93    50    57    48    53    82    70    57
9    J    93    44    90    80    67    67    59    93    54

<br>
3. Identify the function for identifying array’s total number of elements

In [4]:
ans3 = ans2.size
print('Size :  ',ans3)

Size :   100


<br>
4. Create a random integer sample vector of dimension 100, where all the elements are  less than or equal to 50. Using the array indexing concept, retrieve the vector’s last and  second last elements.

In [5]:
np.random.seed(100)
ans4 = np.random.randint(0,50,size=(1,100))
print('Original Vector :  ',ans4,end='\n\n',sep='\n')
print('Last 2 elements :  ',ans4[:,-2:])

Original Vector :  
[[ 8 24  3 39 23 15 48 10 30 34  2 34 14 34 49 48 24 15 36 43 16  9 29 22
   2 27 44  4 31  1 13 19 36  4 27  3  7 49 47  1 14  7 16  2 41 30 19 34
  27 46 49 30 48 47 39 45 38 44 18  0 34 10 17  8 13 42 30 17  4 40 27 27
  19 14  0 13 12 42  3  6  3 20 15 10 23 47  3 41 48 43 36  5  7 38 22 30
  34 42 20 31]]

Last 2 elements :   [[20 31]]


<br>  
5. Create a random sample matrix, A, of dimension 5x5 and extract the subarray, B of size  2x2, from the bottom left corner of A

In [6]:
np.random.seed(100)
ans5_1 = np.random.randint(10,80,size=(5,5))
ans5_2 = ans5_1[-2:,:2]
print('5x5 Matrix :  ',ans5_1,sep='\n',end='\n\n')
print('2x2 Bottom left :  ',ans5_2,sep='\n')

5x5 Matrix :  
[[18 34 77 58 20]
 [62 63 76 24 44]
 [34 25 70 68 26]
 [19 12 37 14 41]
 [11 23 14 69 77]]

2x2 Bottom left :  
[[19 12]
 [11 23]]


<br>  
6. Convert a random sample 10x10 matrix into a 20x5 matrix  

In [7]:
np.random.seed(100)
arr = np.random.randint(0,100,size=(10,10))
print("Array 10x10 Shape :  ",arr.shape,sep='\n',end='\n\n')
ans_6 = arr.reshape((20,5))
print('Reshaped 20x5 array Shape :  ',ans_6.shape,sep='\n')

Array 10x10 Shape :  
(10, 10)

Reshaped 20x5 array Shape :  
(20, 5)


<br>  
7. Split the feature array X = [34, 67, 42, 37, 88, 50, 77, 94, 34, 74] into three other  matrices. The splitting points are 37 and 94.

In [8]:
X = [34, 67, 42, 37, 88, 50, 77, 94, 34, 74]
ans7_1 = X[:X.index(37)]
ans7_2 = X[X.index(37):X.index(94)]
ans7_3 = X[X.index(94):]
print('Matrix 1 :  ',ans7_1,end='\n\n')
print('Matrix 2 :  ',ans7_2,end='\n\n')
print('Matrix 3 :  ',ans7_3)

Matrix 1 :   [34, 67, 42]

Matrix 2 :   [37, 88, 50, 77]

Matrix 3 :   [94, 34, 74]


<br>  
8. Create a sample sequence of 20 evenly spaced numbers between 10 and 20

In [9]:
ans8 = np.linspace(10,20,20)
print('Sample :  ',ans8,sep='\n')

Sample :  
[10.         10.52631579 11.05263158 11.57894737 12.10526316 12.63157895
 13.15789474 13.68421053 14.21052632 14.73684211 15.26315789 15.78947368
 16.31578947 16.84210526 17.36842105 17.89473684 18.42105263 18.94736842
 19.47368421 20.        ]


<br>  
9. How do you compute the cumulative sum and cumulative product of elements in an array?


In [10]:
X = [2,6,4,3,5,1,9,7,1,5,7,2]
ans9_1 = np.cumsum(X)
ans9_2 = np.cumprod(X)
print('X\tsum\tprod')
for i in range(0,len(X)):
    print(X[i],ans9_1[i],ans9_2[i],sep='\t')

X	sum	prod
2	2	2
6	8	12
4	12	48
3	15	144
5	20	720
1	21	720
9	30	6480
7	37	45360
1	38	45360
5	43	226800
7	50	1587600
2	52	3175200


<br>  
10. Obtain the statistical measures of a randomly defined dataset.


In [11]:
np.random.seed(100)
arr = np.random.rand(50)
print('Mean : ',round(arr.mean(),2))
print('Median : ',round(np.median(arr),2))
print('Mode : ',stats.mode(arr))
print('Variance : ',arr.var())
print('Standard Deviation : ',round(arr.std(),2))

Mean :  0.46
Median :  0.43
Mode :  0.5434049417909654
Variance :  0.0969785877166355
Standard Deviation :  0.31
